import { DEFAULT_LIBRARY_ITEMS, SUBJECTS, buildDefaultState } from './defaultData';
import { CATEGORIES, type AppState } from './types';

const STORAGE_KEY = 'wlp-generator-state-v1';

/** Ensures state has an entry for every current subject/lesson/category, so adding a
 *  subject later (or loading an older save) never leaves the grid/library with holes. */
export function reconcile(state: AppState): AppState {
  const subjects = SUBJECTS;
  const library = { ...state.library };
  for (const subject of subjects) {
    if (!library[subject.id]) {
      library[subject.id] = { LO: [], Activities: [], Consolidation: [], Homework: [] };
    } else {
      for (const category of CATEGORIES) {
        if (!library[subject.id][category]) library[subject.id][category] = [];
      }
    }
    for (const category of CATEGORIES) {
      // Remove legacy single example items generated by the old defaultData
      library[subject.id][category] = library[subject.id][category].filter(
        (item) => item.id !== `${subject.id}-${category}-example`,
      );
      // Sync text of any existing default items to match current DEFAULT_LIBRARY_ITEMS
      DEFAULT_LIBRARY_ITEMS[category].forEach((text, i) => {
        const defaultId = `${subject.id}-${category}-default-${i}`;
        const existing = library[subject.id][category].find((item) => item.id === defaultId);
        if (existing) existing.text = text;
      });
      if (library[subject.id][category].length === 0) {
        DEFAULT_LIBRARY_ITEMS[category].forEach((text, i) => {
          library[subject.id][category].push({ id: `${subject.id}-${category}-default-${i}`, text });
        });
      }
    }
  }

  const weeks = state.weeks.map((week) => {
    const grid = { ...week.grid };
    for (const subject of subjects) {
      if (!grid[subject.id]) grid[subject.id] = {};
      for (let lesson = 0; lesson < subject.periods; lesson++) {
        if (!grid[subject.id][lesson]) {
          grid[subject.id][lesson] = { LO: [], Activities: [], Consolidation: [], Homework: [] };
        } else {
          for (const category of CATEGORIES) {
            if (!grid[subject.id][lesson][category]) grid[subject.id][lesson][category] = [];
          }
        }
      }
    }
    return { ...week, grid };
  });

  const currentWeekId = weeks.some((w) => w.id === state.currentWeekId)
    ? state.currentWeekId
    : (weeks[0]?.id ?? '');

  return { subjects, library, weeks, currentWeekId };
}

export function loadState(): AppState {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return buildDefaultState();
    const parsed = JSON.parse(raw) as AppState;
    if (!parsed.subjects || !parsed.library || !parsed.weeks || !parsed.currentWeekId) {
      return buildDefaultState();
    }
    return reconcile(parsed);
  } catch {
    return buildDefaultState();
  }
}

export function saveState(state: AppState): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    // localStorage unavailable (e.g. private browsing quota) - fail silently, in-memory state still works
  }
}

/** Validates and normalises a parsed backup file before it replaces the live state.
 *  Throws with a message suitable for display if the file doesn't look like a WLP backup. */
export function parseBackupState(raw: unknown): AppState {
  if (
    !raw ||
    typeof raw !== 'object' ||
    !('subjects' in raw) ||
    !('library' in raw) ||
    !('weeks' in raw) ||
    !('currentWeekId' in raw) ||
    !Array.isArray((raw as AppState).weeks)
  ) {
    throw new Error("This file doesn't look like a WLP Generator backup.");
  }
  return reconcile(raw as AppState);
}
